apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: replicasetapp
spec:
  selector:
    matchExpressions:
      - key: app
        operator: Exists
  replicas: 3
  template:
    metadata:
      labels:
        name: new-app
        app: replicasetapp  # `replicasetapp` matches the selector criteria
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 80
              name: http
              protocol: TCp
